export const MESSAGE_TYPES = Object.freeze({
  PING: "PING",
  GET_STATUS: "GET_STATUS",
  GET_SETTINGS: "GET_SETTINGS",
  SAVE_SETTINGS: "SAVE_SETTINGS",
  OPEN_DASHBOARD: "OPEN_DASHBOARD",
  CRAWL_CREATE: "CRAWL_CREATE",
  CRAWL_START: "CRAWL_START",
  CRAWL_PAUSE: "CRAWL_PAUSE",
  CRAWL_RESUME: "CRAWL_RESUME",
  CRAWL_CANCEL: "CRAWL_CANCEL",
  GET_CRAWL_SUMMARY: "GET_CRAWL_SUMMARY",
  GET_AGENT_EVENTS: "GET_AGENT_EVENTS"
});

export const MESSAGE_TYPE_SET = new Set(Object.values(MESSAGE_TYPES));
